modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/K1miram/attribute-randomizer/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/project/a2l3d92F"
logoFile="assets/attributerandomizer/icon.png"
authors="Kimiram"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[26.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"